- job:
    name: testjob
    run: playbooks/testjob.yaml

- project:
    name: ZuulOrgnization/zuul-test
    check:
      jobs:
        - noop
        - testjob
    gate:
      jobs:
        - testjob
